#! /bin/sh

##################################################
#                    Config                      #
##################################################
bspc config border_width         2
bspc config window_gap          20 # default = 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config click_to_focus       true

bspc monitor -d I II III IV V VI VII VIII IX X

##################################################
#                    Rules                       #
##################################################
bspc rule -a Chromium desktop=^4
bspc rule -a discord desktop=^10 state=fullscreen

# Start lemonbar
panel &
