#! /bin/sh

##################################################
#                    Config                      #
##################################################
bspc config border_width         2
bspc config window_gap          20 # default = 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config click_to_focus       true

bspc monitor -d I II III IV V VI VII VIII IX X

for m in $(bspc query -M); do
    bspc monitor $m -d $(echo -e 'I') $(echo -e 'II') $(echo -e 'III') $(echo -e 'IV')
    #bspc monitor $m -d $(echo -e '\ue174') $(echo -e '\ue175') $(echo -e '\ue176') $(echo -e '\ue177')
done

# Start lemonbar
panel &
